name: Manual Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0, 1.0.0-rc.1, 1.0.0-snapshot.123)'
        required: true
        type: string
      tag:
        description: 'NPM dist-tag (latest, rc, snapshot, beta, alpha)'
        required: true
        type: choice
        options:
          - latest
          - rc
          - snapshot
          - beta
          - alpha

permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update version
        run: npm version ${{ inputs.version }} --no-git-tag-version

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: npm publish --provenance --access public --tag ${{ inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release (if latest)
        if: inputs.tag == 'latest'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.version }}
          name: Release v${{ inputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          echo "## 📦 Manual Publish Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: \`${{ inputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **NPM Tag**: \`${{ inputs.tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Package**: [@baikenlabs/weaver](https://www.npmjs.com/package/@baikenlabs/weaver)" >> $GITHUB_STEP_SUMMARY
